# Generated by Django 4.2.6 on 2023-10-30 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inductors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('manufacter', models.CharField(blank=True, max_length=50)),
                ('step', models.DecimalField(decimal_places=1, max_digits=3)),
                ('length', models.IntegerField(default=150)),
                ('wind_size', models.IntegerField(default=150)),
                ('sezi_of_detail', models.CharField(blank=True, max_length=50)),
                ('len_of_tube', models.IntegerField(default=150)),
                ('notice', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power_of_machine', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TubeShapes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thinks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TestInductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=50)),
                ('power', models.IntegerField()),
                ('voltage', models.IntegerField()),
                ('currency', models.IntegerField()),
                ('freq', models.DecimalField(decimal_places=1, max_digits=3)),
                ('inductor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.inductors')),
                ('machine_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.machines')),
            ],
        ),
        migrations.AddField(
            model_name='inductors',
            name='tube_shape',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.tubeshapes'),
        ),
    ]
