# Generated by Django 4.2.6 on 2023-10-31 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_inductors_manufacter_alter_inductors_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inductors',
            name='manufacter',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inductors',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='testinductor',
            name='inductor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.inductors'),
        ),
    ]
