# Generated by Django 4.2.6 on 2023-10-31 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_inductors_manufacter_alter_inductors_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinductor',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.machines'),
        ),
    ]
