# Generated by Django 4.2.6 on 2023-10-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_testinductor_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inductors',
            name='photo',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
